apiVersion: apps/v1
kind: Deployment
metadata:
  name: edukate
  namespace: default
  labels:
    app: edukate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edukate
  template:
    metadata:
      labels:
        app: edukate
    spec:
      containers:
        - name: edukate
          image: igbedo/edukate:main-6580331f-1671154818 # {"$imagepolicy": "flux-system:edukate-gitops"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
