apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: igbedo/edukate
    newName: igbedo/edukate # {"$imagepolicy": "flux-system:edukate-gitops:name"}
    newTag: main-1e386774-1668823041 # {"$imagepolicy": "flux-system:edukate-gitops:tag"}
