apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: igbedo/edukate
    newName: igbedo/edukate # {"$imagepolicy": "flux-system:edukate-gitops:name"}
    newTag: main-d5a8892b-1668543264 # {"$imagepolicy": "flux-system:edukate-gitops:tag"}
